Merge techpriest's edits
RkShaRkz/Starsector-IntelliJ-Template pull request #25
Opened 2024-07-22 21:33 UTC by meelock

VERY WIP, needs a lot of auditing. Also need the main mod file to be merged, still figuring that out.

2024-07-22 21:42 UTC, RkShaRkz requested changes
As mentioned offline on Slack, this will need considerate changes. I'll walk you through the general idea due to any "contribution guideline" lacking.

2024-07-22 21:42 UTC, RkShaRkz commented on src/data/scripts/ai/VayraAntiFighterAI.java
> +import com.fs.starfarer.api.combat.ShipCommand;
unnecessary change really

2024-07-22 21:42 UTC, RkShaRkz commented on src/data/scripts/ai/VayraAntiFighterAI.java
> +    private final boolean OVERSTEER=true;  // REQUIRES NO OVERSHOT ANGLE!
another similar one

2024-07-22 21:42 UTC, RkShaRkz commented on src/data/scripts/ai/VayraAntiFighterAI.java
> +
no. please no :)

2024-07-22 21:42 UTC, RkShaRkz commented on src/data/scripts/ai/VayraAntiFighterAI.java
> +                ){
please revert so they're lined up. yes i know autoformatter has a problem with this, it needs to be fixed manually.

2024-07-22 21:42 UTC, RkShaRkz commented on src/data/scripts/ai/VayraAntiFighterAI.java
> +        timer+=amount;
no. spaces between arithmetic operations please.

2024-07-22 21:42 UTC, RkShaRkz commented on src/data/scripts/ai/VayraAntiFighterAI.java
> +            timer -=check;
identical commen (ditto)

2024-07-22 22:55 UTC, RkShaRkz requested changes
Please delete `VayraTags` and get rid of all it's usages. It's the wannabe crashcode that vayra had in, when you used DiableAvionics and some other mods that people still kinda use today.

2024-07-22 22:55 UTC, RkShaRkz commented on src/data/scripts/campaign/KadurBlueprintStocker.java
> +import static data.scripts.VayraTags.readSpecial;
no no, get rid of this file immediatelly.

2024-07-22 22:57 UTC, RkShaRkz commented
But - looking much better. Dropped 600 lines of changes by just using a similar formatter?

2024-07-23 03:17 UTC, RkShaRkz requested changes
Plenty of stuff to go through before I do another CR pass.

Please address CR comments and answer questions, thank you.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/KadurBlueprintStocker.java
> +        doSpecial(amount);
needs to go away.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/KadurBlueprintStocker.java
> +        log.info(String.format("Starting stockKadurBlueprints scan"));
unnecessary `String.format` call. you use it like this
```
Object message = whatever; //or exception.getMessage()
int quantity = performSomeCalculations();
String.format("The message is %s and the quantity is %d", message, quantity)
```

without the parameters, you're formatting a static string into itself. it's surely underlined yellow and pressing alt+enter on it will offer to remove it.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/KadurBlueprintStocker.java
> +
this method slowly makes everyone in the sector hate you. Sure, it only does it one faction at a time. But have this method run enough times and, well, the whole universe will hate you if you're using DiableAvionics.

look at https://github.com/RkShaRkz/Starsector-IntelliJ-Template/pull/9/commits/b5ac7d64cc6b51e47142533272c2c218d1461d65

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/KadurBlueprintStocker.java
> +        log.info(String.format("Starting stockKadurWeapons scan"));
identical String.format() comment as above. why did you even add it?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/econ/CaliphOrbitalStation.java
> +public class CaliphOrbitalStation extends OrbitalStation implements FleetEventListener {
javadoc everywhere? Or on class?

what does this class even do?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/econ/KadurHardenedPopulace.java
>  public class KadurHardenedPopulace extends BaseMarketConditionPlugin {
similar hypocritical comment about javadoc on this class even though it's lacking in my fork too :D

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/econ/KadurMajority.java
> -    };
hm. why is this a hardcoded array. even then, it being static is a bad thing, because it will forever leak.

can you please check usages of this? in my sourceset, it's referenced only once, in the `apply()` method. please drop the `static` modifier. as far as it being an array - meh. can remain, i'm not going to nitpick.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/econ/KadurMajority.java
> +	}
So...

if "kadur_remnant" contains this market's faction ID - then do one thing,
otherwise, if "kadur_remnant" is not empty - do another thing.

what happens in the third case - when this market's factionId isn't "kadur_remnant" and "kadur_remnant" faction markets are empty?

Instead of logging, i believe we should send some more visible message to the player, so he can notify us of the problem.

Please add a ` } else { notifyPlayer(); }` branch to catch this case, and look into how to paste messages onto the screen.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/econ/vayra_virus_bomb.java
> +    private final int PRODUCTION_MALUS=-1;
spaces

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/econ/vayra_virus_bomb.java
> +public class vayra_virus_bomb extends BaseHazardCondition {
classes don't use snake_case naming, we use UpperCamelCase for class names, so please fix if possible.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/fleets/KadurQamarSpawner.java
> +import java.util.Random;
why?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/fleets/KadurQamarSpawner.java
> +    private static final int BASE_LIGHT = 2;
why change this? why change the 0/1/3 (heavy/medium/light) distribution into 1/0/2 ?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/fleets/KadurQamarSpawner.java
> +import java.util.Random;
doesn't even seem to be used. please reformat and optimize imports on the whole codebase.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k1.java
> +public class vayra_k1 extends BaseCommandPlugin {
do i want to ask what this command even does?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k2.java
> +public class vayra_k2 extends BaseCommandPlugin {
do i want to ask what this command even does?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k3.java
> +public class vayra_k3 extends BaseCommandPlugin {
identical comment...

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k4.java
> +public class vayra_k4 extends BaseCommandPlugin {
and again

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k7.java
> +public class vayra_k7 extends BaseCommandPlugin {
and again.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k3.java
> +                Misc.setSalvageSpecial(dialog.getInteractionTarget(), data);
please extract these strings as either `public final` fields in this class or - actually no. let's not make a new Constants/StringConstants file, lets just keep them as 
```
public final String SERAPH ="vayra_seraph_standard";
public final String HOLY_SWORD = "KHS Holy Sword";
public final String KADUR_REMNANT = "kadur_remnant";
```
here.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k4.java
> +                data.addShip(new ShipRecoverySpecial.PerShipData(variant, ShipRecoverySpecial.ShipCondition.GOOD, "KHS Ceto", Factions.HEGEMONY, 0f));
identical string extraction comment here

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/campaign/vayra_rulecmd/vayra_k7.java
> +                        NexConfig.getFactionConfig("kadur_remnant").getStartFleetSet(NexFactionConfig.StartFleetType.GRAND_FLEET.name()).addFleet(caliphFleet);
no hardcoded strings please. since some of these definitely repeat between my previous couple of comments - lets make a StringConstants file and extract all of them there. and yes, then they could be `public static final` instead.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraGuardianIFF.java
> +    }*/
why get rid of this?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraGuardianIFF.java
> +        if ((Global.getSettings().getModManager().isModEnabled("better_deserving_smods") ? Global.getSettings().getBoolean("BuiltInSMod") && ship.getHullSpec().isBuiltInMod("vayra_kadur_iff") : ship.
no hardcoded strings please, extract to this file.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraGuardianIFF.java
> +        if ((Global.getSettings().getModManager().isModEnabled("better_deserving_smods") ? Global.getSettings().getBoolean("BuiltInSMod") && ship.getHullSpec().isBuiltInMod("vayra_kadur_iff") : ship.
in fact, simplify/extract this condition.

```
if (shouldApplyBetterStats()) {
// apply 10% increases
/*
 ...
*/
} else {
// otherwise apply 5% increases
}
```

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraGuardianIFF.java
> +        }
lets rewrite this
```
boolean shipIsNonNull = ship != null;
boolean shipHasNoFighterBays = true;
if (shipIsNonNull) {
    shipHasNoFighterBays = (ship.getHullSpec().getFighterBays() < 1 || ship.getHullSpec().getBuiltInWings().size() < 1 || !ship.getVariant().hasHullMod(HullMods.CONVERTED_HANGAR));
}

if (shipIsNonNull && shipHasNoFighterBays) {
    return NO_FIGHTER_BAYS;
}

return null;
```

with the `private final String NO_FIGHTER_BAYS = "Ship has no fighter bays"` extracted at the top of the class

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraGuardianIFF.java
> +        }
ugh... by now, we'd have extracted some strings to the new StringConstants file. see which ones are reusable from there, extract the rest to the StringConstants file.

remember, zero hardcoded strings policy :) no magic numbers (other than 0 or 1), no hardcoded strings.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraGuardianIFF.java
> +        }
that being said, extract `10f` as `Float STAT_BONUS = 10f;`

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraSecretMartyrBuff.java
> +import com.fs.starfarer.api.combat.WeaponAPI;
i dont get why it changed the `.* ` import to individual ones. you need to reformat/reorganize imports using my formatter :)

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraSecretMartyrBuff.java
> +    private static final float BUFF_THRESHOLD = 0.33f;
why?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraSecretMartyrBuff.java
> +            float effectLevel = MathUtils.clamp(1f - (ship.getHullLevel()*3), 0f, 1f);
i kinda liked "my" old version better.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraSecretMartyrBuff.java
> +            ship.setJitterUnder(this, BUFF_GLOW_COLOR, effectLevel*0.2f, 7, 10f);
?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/VayraSecretMartyrBuff.java
> +            //stats.getCriticalMalfunctionChance().unmodify(buffId);
this doesn't make sense. i checked. the stats never originally modified these three.

please delete this commented out code.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +            return "" + Math.round(ANTIFTR_BONUS) + "%";
this is where we should use `String.format()`

```
return String.format("%f%%", Math.round(ANTIFTR_BONUS));
```

I mean, adding an empty string to a number then to another string is idiotic. if we're taking a "convert to string" shortcut, adding to "%" is enough.

but since it looks like crap, it should be improved.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +            return "" + Math.round(RANGE_BONUS) + "%";
identical comment as above

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +            return "" + Math.round(Math.abs(AUTOFIRE_PENALTY) * 100f) + "%";
and again.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +        //stats.getRecoilPerShotMult().modifyPercent(id, RECOIL_PENALTY);
why?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +            if ((stats.getVariant().hasHullMod("vayra_slow_autoforge") && stats.getVariant().hasHullMod("vayra_modular_engines")) || !stats.getVariant().hasHullMod("vayra_modular_engines")) {stats.ad
extract strings please :)

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +        }
tabs are 4 spaces each. please address so it's consistent with the rest of the codebase.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_caliph_core.java
> +				if (fighter != null && fighter.hasTag("kadur")) {return (int) fighter.getOpCost(null)/2;}
why are we returning half cost here?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_forever_war.java
> +        FUEL_EFF.put(HullSize.CAPITAL_SHIP, 2.5f);
why?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_forever_war.java
>      }
hmm... i'm not quite getting this yet. please explain this bit to me.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_forever_war.java
> +        stats.getOverloadTimeMod().modifyMult(id, OVERLOAD_REDUCTION);
so it wants to get away with just 10% overload duration? :D heh. kinda cheaty.

where's this hullmod used? please check number of references. we probably won't end up using 0.9 for it.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +import static data.scripts.KadurModPlugin.VAYRA_DEBUG;
You'll probably want to use `VayraMergedModPlugin.VAYRA_DEBUG` here

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +    public static ArrayList<String> EXCLUDED_HULLMODS = new ArrayList<>(Arrays.asList(
old (my) solution was better. please revert to `Collections.singletonList()`

in fact, use this.
```
public static List<String> EXCLUDED_HULLMODS = Collections.singletonList(HullMods.MAKESHIFT_GENERATOR);
```

remember, always declare variables using a supertype, and instantiate using a concretized type. e.g.
`List<String> myList = new ArrayList<String>()` because otherwise we're leaking implementation-specific details outside, and there's no need for anyone who references `myList` to know, or care, what kind of `List` the `myList` variable actually is.

Caller's code should work the same regardless if it's `ArrayList`, `LinkedList`, `Vector`, `CopyOnWriteArrayList` or `Stack`

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +    private static final class JitterData {
👍

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +        //LocalData localData = getLocalData(engine);
delete? why are we keeping this garbage here?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                    if (ship.getParentStation() != null && !ship.getCustomData().containsKey("vayra_apply_dmod") && ship.getParentStation().getHullSpec().getHints().contains(ShipHullSpecAPI.ShipTypeH
aha, so the old `doEveryOtherPartStuff(ship, amount, engine);` code was extracted into these new classes...

well then. extract strings and these numbers.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                if (!shieldHit) damage.getModifier().modifyMult("vayra_modular_shields", 0.02f);
extract this 0.02, whatever it is.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +    public static class EXP3doEveryOtherPartStuff implements DamageTakenModifier {
this doesn't need to be public either, right?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +    public static class EXPdoEveryOtherPartStuff implements DamageTakenModifier {
ditto

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                        for (ShipAPI check : CombatUtils.getShipsWithinRange(target.getLocation(), 1000)) {
extract

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                                    && ship.getParentStation().equals(check.getParentStation())))) {
see, this is an ideal textbook example of why sometimes conditions should be extracted into booleans outside of the `if` statement, then just using those new variables in the `if()` statement.

this looks like it's doing nonNull AND nonNullHullId AND hullIdIsShieldGenerator OR shipHasParentStation AND parentStationNonNull, but it's really checking `nonNull AND nonNullHullId AND hullIdIsShieldGenerator OR (shipHasParentStation AND parentStationNonNull)`

either way, extracting these checks into boolean significantly improves readability and skimability of the code. please change.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                        damage.getModifier().modifyMult("vayra_modular_shields", generator.getFluxTracker().isOverloadedOrVenting() ? 1f : Math.max(0.1f, generator.getFluxTracker().getFluxLevel()*0.9
extract crap outside. especially this 0.9f, wtf is it even supposed to be doing here? why isn't this `vayra_modular_shields` extracted as a `public final String BUFF_ID = "vayra_modular_shields";` ?

so if the ship is overloaded, we take 100% damage, but otherwise we clamp it between (10%,90%) ? don't get why but alright. perhaps you can explain better.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +        ShipAPI generator = (ShipAPI) ship.getCustomData().get(STORED_GENERATORS_KEY);//localData.storedGenerators.get(ship);
unnecessary comments are unnecessary.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                    ship.setCustomData(STORED_GENERATORS_KEY, generator);//localData.storedGenerators.put(ship, generator);
identical comment.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +            if (ship.getCustomData().containsKey(JITTER_KEY)/*localData.jitters.containsKey(ship)*/) {
same.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                    ship.removeCustomData(JITTER_KEY);//localData.jitters.remove(ship);
same. fortunatelly, everything is already extracted into constants :)

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +        //if (fluxDecrease > 0.1f) Global.getCombatEngine().addFloatingText(new Vector2f(ship.getLocation().x+200f, ship.getLocation().y), String.valueOf(fluxDecrease), 30f, Color.BLUE, ship, 1f, 0.5
same

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +        ShipAPI generator = (ShipAPI) ship.getCustomData().get(STORED_GENERATORS_KEY); //localData.storedGenerators.get(ship);
same

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +                    ship.setCustomData(STORED_GENERATORS_KEY, generator);//localData.storedGenerators.put(ship, generator);
same. just so we're on the same page - we don't want inline comments to tell us *nothing* about the *WHY*.

comments are there to tell us about the *WHY* not about *HOW* or especially not about *HOW WE USED TO*.
just get rid of all of this commented out code.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_modular_shields.java
> +    private static void triggerShield(ShipAPI ship, ShipAPI source, Vector2f point, Float damage, DamageType type, ShipAPI generator, Color color, Boolean hard) {
why is this static? remember ,static methods cause memory leaks[*]. lets not have static methods if we can. and we surely somehow can. lets deal with that problem when we get to it. please remove `static`

[*] - static methods don't cause leaks, but they make deducing when to GC something harder, and thus waste more memory than necessary or prevent this object from being GC'd at all, thus effectivelly causing a memory leak.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_sometimes_war.java
> +        FUEL_EFF.put(HullSize.CAPITAL_SHIP, 2.5f);
again, why cripple these constants? what does "git blame" say about these lines? does the commit where they're introduced say anything good?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_sometimes_war.java
> +            return "" + (int) (SHIELD_UPKEEP * 100f) + "%";
i believe we already mentioned this textbook case for String.format()

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_sometimes_war.java
> +        float opad = 10f;
extract

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/hullmods/vayra_targeting_core.java
> +        stats.getEnergyWeaponRangeBonus().modifyPercent(id, RANGE_BONUS);
now why the fuck did he change multiplying by 1.5 to modifying by 50% percent. unnecessary change is unnecessary.

does the git blame say anything about why this was done?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/plugins/KadurProjHandlerPlugin.java
> +import com.fs.starfarer.api.combat.WeaponAPI;
hm. still looks like we're not using the same code style options but fine.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/plugins/KadurProjHandlerPlugin.java
> +    private static final float ROD_ARC_RANGE = 150f; // check for ships whose collision radius intersects or is within circle
i want to ask why.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/plugins/KadurProjHandlerPlugin.java
> +    private List<DamagingProjectileAPI> boomerangShields = new ArrayList<>();
i'm gonna have to insist on bringing those `final` keywords back please.

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/plugins/KadurProjHandlerPlugin.java
> +                            for (int p = 0; p < (int) (CANISTER_SPIKES * 3); p++) {
`CANISTER_SPIKES` is already an int. what is this cast trying to achieve here?

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/plugins/VayraSplinterPlugin.java
> +import static data.scripts.KadurModPlugin.VAYRA_DEBUG;
already mentioned - `VayraMergedModPlugin`

2024-07-23 03:17 UTC, RkShaRkz commented on src/data/scripts/plugins/VayraSplinterPlugin.java
> +        if (ship != null && ship.isAlive()) {
👍

2024-07-24 17:32 UTC, RkShaRkz commented
How did we go from +1600/-900 to +2,710 −795? :)
Also, how come zero comments have any feedback/replies on them?

2024-07-25 05:45 UTC, meelock commented
> How did we go from +1600/-900 to +2,710 −795? :) Also, how come zero comments have any feedback/replies on them?

This draft will disappear when I get around to splitting up the changes. We went up so high because I missed over half the actual changes techpriest made.

2024-08-03 19:28 UTC, RkShaRkz commented
@meelock whats the status on this one? I take it you'll ping me or request another review when you're done with your things?
Do make sure that VayraTags file is not in the code you plan on merging.

2024-09-27 13:48 UTC, RkShaRkz commented
@meelock so, do we close this or what?

2024-09-28 22:22 UTC, meelock commented
I apologize, I need to close this and split the changes, but I'm not even sure I got all of them. I might just pr some of the minor changes later next week. School started again, and as I was not feeling up for the changes this summer, this PR is kinda in limbo.

2024-09-29 16:39 UTC, RkShaRkz commented
> I apologize, I need to close this and split the changes, but I'm not even sure I got all of them. I might just pr some of the minor changes later next week. School started again, and as I was not feeling up for the changes this summer, this PR is kinda in limbo.

well, sad to hear that but in that case, i suggest it'd be best for it to get closed and restarted from scratch.
you fork a copy, sync to your local branch and when you get things working on your end submit a new PR which will go through the same review process like this one. do try to take the current review comments as "most likely still applicable to the future PR" but I really wanna clean up any VayraMerged-related outstanding PRs out of the way.

2024-09-29 16:39 UTC, closed without merging